local_def: &local_def
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  <<: *local_def
  database: evobot-development

staging:
  <<: *local_def
  database: evobot-development

development:
  <<: *local_def
  database: evobot-development

test:
  <<: *local_def
  database: evobot-test
